spring:
  datasource:
    url: jdbc:postgresql://ep-long-rain-a1o2befc-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_CY4UiVPg7dko
  jpa:
    hibernate:
      ddl-auto: validate          # 스키마는 Flyway로 관리 (운영 권장)
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
